### ISSUE TITLE
Upload Logo

### ISSUE THREAD

**Issue by francesco-vannini** [PiSupply/Fish-Dish#1]
![fish-dish](https://user-images.githubusercontent.com/16068311/30545403-64f9ba94-9c81-11e7-8426-04ae35065ff7.png)

**Comment by francesco-vannini** [comment]
Use this thread to add pictures

**Comment by francesco-vannini** [comment]
![fish-dish](https://user-images.githubusercontent.com/16068311/30547059-36f2d874-9c86-11e7-8705-9f795ea5f0a1.png)

**Comment by ChristopherRush** [comment]
![fish-dish-github-banner](https://user-images.githubusercontent.com/1878314/73873949-85ee7b00-484a-11ea-860d-a3a5d146f1a9.png)
